import "./globals.css";
import { HackWrapper } from "@/context";
import { ClerkProvider } from '@clerk/nextjs'



export const metadata = {
  title: "Blockchain",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider publishableKey= {process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}>
    <html lang="en" className="dark">
      <body
        className={``}
      >
        <HackWrapper>
          {children}
        </HackWrapper>
      </body>
    </html>
    </ClerkProvider>
  );
}
